### ISSUE TITLE
API 로직 추상화, Kakao Oauth 적용

### ISSUE THREAD

**Issue by semnil5202** [ConceptBe/conceptbe-frontend#1]
### ✨ Describe

* 기존에 작성한 API 로직을 추상화 합니다.
* Kakao Oauth를 수행합니다.

### ✅ Tasks

- [x] API 로직 검토
- [x] Kakao Oauth 수행
- [x] 비회원일 경우 회원가입 진행
