### ISSUE TITLE
게시글 상세 및 댓글, 답글 세부 스킬에서 대표 스킬로 변경

### ISSUE THREAD

**Issue by semnil5202** [ConceptBe/conceptbe-frontend#103]
### 🔨 Describe

게시글 상세 및 댓글, 답글의 프로필 영역 중 세부 스킬 대신 대표 스킬로 변경합니다.

서버 API 수정 후 반영합니다.

### ✅ Tasks
- [x] 세부 스킬에서 대표 스킬로 타입 변경
- [x] 프로필 영역 대표 스킬로 UI 표시
- [ ] 서버 API 수정 확인
