### ISSUE TITLE
회원 탈퇴 기능 수정 사항 대응

### ISSUE THREAD

**Issue by semnil5202** [ConceptBe/conceptbe-frontend#143]
### 🔨 Describe

회원 탈퇴 기능으로 인한 서버 수정 사항에 대응합니다. 탈퇴한 회원은 작성한 게시글 모두 삭제, 프로필 페이지가 삭제됩니다. 추가로 작성한 댓글은 댓글 틀만 남겨지고 프로필 정보, 작성한 댓글에 대해서는 '탈퇴한 회원', '삭제된 댓글입니다.'의 형식으로 수정됩니다.

### ✅ Tasks
- [x] 회원 탈퇴 기능
- [ ] 탈퇴한 회원이 작성한 게시글(삭제된 게시글) 접근 시 404 -> (현재는 500 에러, 서버 수정 완료 시 Alert로 우회할 예정)
- [ ] 탈퇴한 회원 프로필 페이지 접근 시 404 -> (현재는 500 에러, 서버 수정 완료 시 Alert로 우회할 예정)
- [x] 탈퇴한 회원이 작성한 댓글 또는 답글의 프로필 영역을 기본이미지 + '탈퇴한 회원' 으로 초기화
- [x] 탈퇴한 회원이 작성한 댓글 또는 답글의 스킬 영역을 '-'로 초기화
- [x] 탈퇴한 회원이 작성한 댓글 또는 답글의 내용 영역을 '삭제된 댓글입니다.' 로 초기화
- [x] 탈퇴한 회원이 작성한 댓글 또는 답글에 좋아요 기능은 가능

### 🙋🏻 More

![image](https://github.com/ConceptBe/conceptbe-frontend/assets/89172499/bc7b2b8b-f59a-429d-96f7-73f5e0fa68b0)
