### ISSUE TITLE
게시글에서 이미지 클릭 시 케러셀 전체 화면으로 보여주는 기능

### ISSUE THREAD

**Issue by yogjin** [ConceptBe/conceptbe-frontend#165]
### ✨ Describe

<img width="1025" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/ed3f8670-5b9f-42d4-b860-4c037ec04e6b">

### ✅ Tasks

- [ ] 게시글 클릭 시 이미지가 전체화면으로 보인다
- [ ] 좌우로 넘길 수 있다
- [ ] 오른쪽 위를 보고 몇번째 사진인지 알 수 있다
