### ISSUE TITLE
이미지 상세 보기 상하 비대칭 문제 및 압축 값 조정

### ISSUE THREAD

**Issue by semnil5202** [ConceptBe/conceptbe-frontend#169]
### 🔨 Describe

* 이미지 상세 보기 상하 비대칭 문제 해결
* 이미지 압축 값 상향 조정
* 이미지 수정 시 최대 업로드 개수 로직 에러 수정
* 이미지 추가 시 최대 업로드 개수 로직 보완

### ✅ Tasks

- [x] 이미지 상세 보기 상하 비대칭 문제 해결
- [x] 이미지 압축 값 상향 조정
- [x] 이미지 수정 시 최대 업로드 개수 로직 에러 수정
- [x] 이미지 추가 시 최대 업로드 개수 로직 보완
