### ISSUE TITLE
피드 필터 기능

### ISSUE THREAD

**Issue by yogjin** [ConceptBe/conceptbe-frontend#23]
### ✨ Describe

피드 필터링 기능을 추가합니다
<img width="494" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/8e90c393-c8bf-4d1b-87a3-fadb3d3cb095">

<img width="501" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/e50bbe38-3970-4c7b-ad39-697c610d1137">

### ✅ Tasks

`Feed.tsx` 피드 페이지 내부 필터링 기능 추가

### 정책 Descriptions

- [x] 각 필터 내 선택값에 대한 조건은 ‘or조건’
EX : 분야에서 제품과 영화/웹툰을 선택하면, 게시글 중 ‘분야’를 선택한 게시글과 ‘영화/웹툰’을 선택한 게시글을 모두 보여준다
- [x] 필터 간의 조건은 ‘and조건’
EX : 분야에서 ‘제품’을 선택하고, 목적에서 ‘사이드프로젝트’를 선택하면, ‘분야=제품 & 목적=사이드프로젝트’인 게시글을 보여준다
- [x] 필터는 ‘피드(FD)’ 화면 위에 팝업으로 띄우며, 필터가 떠 있을 때, 뒤쪽의 피드 영역은 비활성화 처리 한다 (조작불가)
- [x] 필터 적용된 상태에서, 다시 필터 버튼을 누르면, 기존 셋팅값이 유지된 상태로 팝업된다
- [x] 필터를 한번 적용하면, 타 페이지 이동 후 다시 피드(FD) 페이지로 돌아와도 적용한 필터가 유지되어야 한다
- [x] 모든 필터는 ‘글쓰기 상세(DT)’ 에서 등록한 정보를 기준으로 필터링한다

a. 분야 & 목적
- [x] 디폴트로 비활성화 되어있다
- [x] 활성화 버튼 선택 시 : 비활성화
- [x] 비활성화 버튼 선택 시 : 활성화

b. 협업방식 (라디오버튼)
- [x] 디폴트로 ‘상관없음’에 선택되어 있다
- [x] 라디오 버튼으로 셋 중 하나만 선택 가능

c. 지역 (드롭다운)
- [x] 시/도 레벨만 선택 가능 (특별시, 광역시, 도)

d. 팀원모집 (드롭다운)
- [x] 1개만 지정 가능
- [x] 대분류 선택 시, 해당 하위 상세 분류 선택 가능
- [x] 선택한 ‘대분류, 상세분류’의 글자 길이에 따라서, 드롭박스 가로 길이를 조정한다

e. 적용 버튼
- [x] 선택 시, 현재 선택값에 따라 피드 게시물을 필터링해서 보여준다
- [x] 아무 필터값을 선택하지 않았더라도 ‘적용’버튼 선택이 가능하다 

f. 닫기 버튼
- [x] 선택 시, 필터를 적용하지 않고 닫는다
- [x] 셋팅한 필터 값은 저장하지 않는다 (초기화됨)
