### ISSUE TITLE
다형성 컴포넌트 책임 분리 및 디자인 시스템 적용

### ISSUE THREAD

**Issue by semnil5202** [ConceptBe/conceptbe-frontend#3]
### 🔨 Describe

* 다형성 컴포넌트 책임 분리를 통해 컴포넌트 스타일 책임을 위임합니다.
* 디자인 시스템을 적용하여 보다 일관되고 빠른 개발을 위한 기반을 다집니다.

### ✅ Tasks

- [x] 다형성 컴포넌트 Interface 검토 및 스타일 책임 위임
- [x] 중복된 스타일 코드 최소화
- [ ] #5
- [x] 디자인 시스템 레포 생성 및 적용
