### ISSUE TITLE
마이페이지(내 프로필) 기능 구현

### ISSUE THREAD

**Issue by yogjin** [ConceptBe/conceptbe-frontend#39]
### ✨ Describe

<img width="434" alt="image" src="https://github.com/ConceptBe/conceptbe-frontend/assets/33623078/63653db2-e5cf-40c8-8020-909fdaeb5ac9">
마이페이지 기능을 구현합니다.

## 정책
각 알파벳에 대응하는 부분은 피그마 "기획"란 참고

마이페이지 화면 GNB 내 MY 클릭 시 접근되는 화면
디폴트 값으로 ‘내가 쓴 글 탭’을 노출.

a. 더보기 
- [x] 선택시 더보기(ET) 화면으로 이동

b. 프로필 사진
- [x] 프로필 설정(PW) 화면에서 설정한 이미지가 있을 시 노출. 
- [x] 설정한 이미지가 없을 경우, 기본 이미지 노출 -> ~~❓기본 이미지 파일 필요~~ 

c. 대표스킬/닉네임 노출 영역
- [x] 프로필 설정(PW) 화면에서 설정한 대표 스킬을 노출한다.
- [x] 대표 스킬 아래에 프로필 설정(PW) 화면에서 설정한 닉네임을 노출한다.

d. 프로필 수정 버튼
- [x] 선택 시 프로필 설정(PW) 화면으로 이동

e. 회사명/지역명 
- [x] 프로필 설정(PW) 화면 내 입력한 선택값 ‘회사명’, ‘지역명’을 순차 노출한다.  값의 유무에 따라 다음과 같은 순서와 형식으로 노출한다.  1) 회사명, 지역명 모두 있는 경우  : ‘회사명  |  지역명’  2) 회사명만 있는 경우 : ‘회사명’   3) 지역명만 있는 경우 : ‘지역명’
- [x] 값이 없는 경우 노출하지 않는다. 

f. 자기소개 
- [x] 프로필 설정(PW) 화면 내 입력한 자기소개 글을 노출한다. 
- [x] 입력된 값이 없을 경우 노출하지 않는다.

g. 스킬
- [x] 프로필 설정 시 입력한 스킬 값 노출

h. 관심 영역
- [x] 프로필 설정 시 입력한 ’가입목적’ 태그 값 노출

i. 아이디어(내가 쓴 글) 탭
- [x] 선택 시, 버튼 활성화
- [x] 하단에 ‘내가 쓴 글 목록’을 h와 같이 노출 

j. 북마크(내가 스크랩한 글) 탭
- [x] 선택 시 버튼 활성화 및 하단 영역 MY.2와 같이 노출
- [ ] 최근 등록순으로 노출.  ❓백엔드 확인요망
- [ ] 게시글 수정되었을 시, 수정된 날짜를 등록일자로 갈음하여, 최신 등록순으로 노출한다. ❓백엔드 확인요망

k. 내가 쓴 글 목록 
- [x] 사용자가 ‘내가 쓴 글’, ‘스크랩한 글’ 선택 시,  선택한 내용에 따라 노출
- [ ] 최근 등록순으로 노출.  ❓백엔드 확인요망
- [ ] 게시글 수정되었을 시, 수정된 날짜를 등록일자로 갈음하여, 최신 등록순으로 노출한다. ❓백엔드 확인요망
- [x] 터치 시 글 상세 페이지(DT) 이동 

l. 글 수정 버튼
- [x] 내가 쓴 글일 경우 나타나는 버튼. 
- [ ] 선택 시 글 수정 화면(WR.1)으로 이동 -> ❗️글 수정 페이지를 만들어야하는 큰 기능이라 따로 이슈 생성
m. 글 삭제 버튼
- [x] 내가 쓴 글 일 경우 나타나는 버튼
- [ ] 선택 시 확인용 알럿(k) 노출

*좋아요 ~ 조회한 사람 수 영역 : 선택해도 아무일도 일어나지 않음

n. 좋아요
- [x] 우측에 좋아요 수 표기  (최대 999개까지 표기. 999개 이상일 경우 999+로 표기)

o. 댓글
- [x] 우측에 댓글 수 표기 (댓글 및 대댓글 수 전체 포괄. 최대 999개까지 표기. 999개 이상일 경우 999+로 표기)

p. 스크랩
- [x] 우측에 스크랩 숫자 표기 (최대 999개까지 표기. 999개 이상일 경우 999+로 표기)

q. 조회한 사람 수 
- [x] 우측에 조회한 사람 수 표기 (최대 999개까지 표기. 999개 이상일 경우 999+로 표기) 

r. 삭제 확인용 알럿
- [ ] ‘예’ 선택 시, 알럿 미노출 처리 및 해당 게시글 삭제
- [ ] ‘아니오’ 선택 시, 알럿 미노출 처리

#### Todo
- [x] 작성한 글이나 북마크한 글이 없을때 대체 렌더링 적용
- [x] feed -> 내 프로필 이동 시 spinner suspense 적용
- [x] 북마크 탭 클릭 시 데이터 불러올때 Suspense는 `<></>`로 아무화면도 출력하지 않음.
  - [ ] 추후 300ms 지나면 Spinner 적용하는 방법도 고려
  - [ ] 북마크 글 정보는 내 프로필 이동할 때 미리 prefetch 적용하면 좋을듯
- [ ] NewIdeaCard.Content 내부 Dropdown 글 삭제, 글 수정 구현 -> 글 수정 api는 백엔드와 논의
