### ISSUE TITLE
MobileView 375px에서 420px로 확장

### ISSUE THREAD

**Issue by semnil5202** [ConceptBe/conceptbe-frontend#65]
### 🔨 Describe

* 기존 모바일 뷰 사이즈를 375px에서 420px로 확장합니다. 가로 사이즈가 375px 이상의 기기에서 좌우 여백이 생기는 문제를 해결하기 위함입니다.

### ✅ Tasks

- [x] MobileView 420px 확장
  - [x] Feed 페이지 420px 대응
  - [x] Profile 페이지 420px 대응 및 프로필 이미지 parent width, height 지정
  - [x] Agreement 페이지 420px 대응 및 이미지 parent width, height 지정
- [x] https://github.com/ConceptBe/conceptbe-design-system/issues/23
- [x] 로직 동작 오류 수정
  - [x] Agreement, SignUp memberInfo 없는 상태에서 진입 시 잘못된 접근 방식으로 판단하여 로그인 창으로 이동
  - [x] 회원가입 시 자기소개 미 전달 오류 수정
  - [x] 댓글, 대댓글 좋아요 cursor pointer 누락
  - [x] 글쓰기 버튼 cursor pointer 누락
  - [x] 피드페이지 상단 글쓰기 아이콘 및 '아이디어 적으러 가기' 를 통해 글쓰기 페이지로 이동 
  - [x] ProfileInfo Skills 개행 디자인 오류 대응
  - [x] 프로필 페이지에서 쓴 글이 없을 시 해당 영역 클릭하여 '글쓰기' 페이지로 이동
  - [x] 프로필 페이지에서 북마크 한 글이 없을 시 '피드' 페이지로 이동
  - [x] 스킬셋 영역 초과 시 레이아웃 뭉개짐 현상 수정
  - [x] 대댓글 삭제 이후에 content가 남아있던 오류 수정
  - [x] 대댓글 생성 시간이 누락된 오류 수정
- [x] 누락된 디자인 시스템 SVG, PNG 적용

### 🙋🏻 More

검수방 해결한 이슈 정리
1. 북마크한 글 없는 상태에서 터치하면 피드로 넘어가야 하는데 안 넘어감
2. 아이디어 적으러가기 눌러도 글쓰기 화면으로 안 넘어감
3. 피드에서 스킬 셋의 내용이 길어질 경우 피드 작성 시간 및 스킬 셋의 레이아웃이 뭉개짐
