### ISSUE TITLE
댓글 및 대댓글 스크롤 오류 수정

### ISSUE THREAD

**Issue by semnil5202** [ConceptBe/conceptbe-frontend#67]
### 🔨 Describe

* 댓글, 대댓글 작성 시 댓글 입력창을 클릭할 때 화면이 확대되는 오류 수정
* 댓글, 대댓글 처음 작성 시 하단에 공백이 생기는 오류 수정

### ✅ Tasks

- [x] 댓글 관련
  - [x] 댓글 입력창 클릭 시 화면이 확대되는 오류 수정
  - [x] 첫 댓글 입력창 클릭 시 하단에 공백이 생기는 오류 수정
  - [x] 가상 키보드 영역보다 윗 단으로 댓글 입력창 생성
- [x] 대댓글 관련
  - [x] 대댓글 입력창 클릭 시 화면이 확대되는 오류 수정
  - [x] 첫 대댓글 입력창 클릭 시 하단에 공백이 생기는 오류 수정
  - [x] 가상 키보드 영역보다 윗 단으로 대댓글 입력창 생성
- [x] Input 태그, Textarea 태그 관련
  - [x] 인풋박스 선택 시, 키패드만 올라오지 않고, 화면 확대까지 되는 오류 수정
