### ISSUE TITLE
UI 및 디자인 시스템 관련 오류 및 필터링 초기화 버튼 수정

### ISSUE THREAD

**Issue by semnil5202** [ConceptBe/conceptbe-frontend#81]
## ✅ Tasks

- [x] BottomSheet 최대 높이 지정 오류 수정
- [x] 최초 회원가입 시 동의화면, 에러 페이지 이미지 최대 비율 420px로 변경
- [x] 내 프로필 북마크 탭에서 아이디어 카드가 기본 사이즈보다 더 큰 문제 해결
- [x] 에러 페이지 폰트 미적용
- [x] 프로필 페이지 헤더 영역 고정 문제 -> 미고정으로 변경 (재확인 결과 고정 방식이 맞음)
- [x] 프로필 수정 닉네임 input placeholder 내용 수정
- [x] 댓글 입력창 작성, 취소 버튼 윈도우 폰트 크기 대응
- [x] 필터 닫기 버튼 추가 및 기존 닫기 버튼을 초기화 버튼으로 수정
