### ISSUE TITLE
댓글 및 답글 일부 조건에서 스크롤 포커싱이 되지 않는 문제 수정

### ISSUE THREAD

**Issue by semnil5202** [ConceptBe/conceptbe-frontend#87]
### 🔨 Describe

* 댓글이 없는 상태에서, 하단 끝까지 스크롤 후 댓글 입력창을 클릭 시 포커싱이 제대로 되지 않습니다.

### ✅ Tasks

- [x] 일부 조건에서 댓글 입력창 포커싱 오류 수정
  - [x] 댓글 입력창이 일부 가려졌을 때 포커싱 미동작 오류 수정
  - [x] 댓글이 하나도 없는 상태에서 댓글 입력창 포커싱 미동작 오류 수정 
- [x] https://github.com/ConceptBe/conceptbe-frontend/issues/70
